### ISSUE TITLE
From stb to image crate: some doubts

### ISSUE THREAD

**Issue by CatCode79** [Davidster/wgpu-sandbox#10]
I'm trying to replace the stb crate with the same hdr functionality in image, I have some doubts about it:
- Do we really need to use the crate half to halve the space used by the hdr image? That by itself makes sense, if only float16 were actually supported by today's hardware. Apart from the ARM architecture the situation is gray: [half float](https://en.wikipedia.org/wiki/Half-precision_floating-point_format#Hardware_support)
- The image used for hdr I've never seen in the game. Once I'm done implementing everything how do I verify that it's ok?

**Comment by Davidster** [comment]
from my (unreliable) memory:

the reason float 16 is needed is for gpu hardware support of hdr textures. I don't think 32 bit is widely supported by gpus. I came across this error at one point and the wgpu team told me in the matrix chat that I should switch to 16 bit

**Comment by Davidster** [comment]
on this page you can see that texture filtering isn't supported on 32bit
https://webgl2fundamentals.org/webgl/lessons/webgl-data-textures.html

**Comment by Davidster** [comment]
![image](https://user-images.githubusercontent.com/2389735/206007755-184403d3-695b-4ff5-899f-8dbaad3b821d.png)

found it lol

**Comment by Davidster** [comment]
You can verify that the hdr environment maps are working well with the environment map gltf file. I made a branch that you can use to verify it: `hdr_env_test_scene` In particular, the metallic balls on the top row should look like this:

![image](https://user-images.githubusercontent.com/2389735/206008898-e17247dd-1255-4801-8781-530c11195f5b.png)

**Comment by CatCode79** [comment]
Nice! Thank you!

**Comment by CatCode79** [comment]
I should have made it, here's my screenshot:
![hdr_sample](https://user-images.githubusercontent.com/12321983/206248682-2c1c91b8-b8a5-4c47-b4c2-b3c2e5fa8d08.png)

**Comment by Davidster** [comment]
this screenshot is with the image crate? looks good to me! feel free to PR

**Comment by CatCode79** [comment]
It is! I do a couple of checks and then open a PR.

Take note there is a "flaw", which I don't think is possible to fix (it was also in the original code). An hdr image (with the native values already processed) has only 3 useful color channels, while in our code we must necessarily use 4 color channels because of the wgpu::TextureFormat::Rgba16Float format (there is no Rgb16Float one).
So between RAM and sending data to the GPU we use a quarter more data than necessary. All in all it is a minor thing, but to be taken into account in case we find an alternative solution.

**Comment by Davidster** [comment]
nice! that's awesome. will be great to get rid of the dependency and have more of the codebase in rust instead of c :).

> we use a quarter more data than necessary

I wonder if texture compression would help mitigate the fact that one channel is being ignored
